application: dbevent2gc
version: dev
runtime: python
api_version: 1

builtins:
- datastore_admin: on
- appstats: on

handlers:
- url: /image
  static_dir: static/image

- url: /style
  static_dir: static/style

- url: /js
  static_dir: static/js

- url: /(.*\.(gif|png|jpg|ico|txt))
  static_files: static/\1
  upload: static/(.*\.(gif|png|jpg))

- url: /event/sync
  script: app.py
  login: admin

- url: /(.*)
  script: app.py
