application: dbevent2gc
version: 1
runtime: python
api_version: 1

handlers:
- url: /image
  static_dir: static/image

- url: /style
  static_dir: static/style

- url: /js
  static_dir: static/js

- url: /(.*\.(gif|png|jpg|ico|txt))
  static_files: static/\1
  upload: static/(.*\.(gif|png|jpg))

- url: /(.*)
  script: app.py

